name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Ändra till din AWS-region om den är annorlunda.

      - name: Build your HTML game
        run: |
          # Här kan du inkludera kommandon för att bygga ditt HTML-spel.

      - name: Deploy to S3
        run: |
          # Här kan du inkludera kommandon för att kopiera dina filer till S3-bucket.
