name: Build and Deploy Game

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build game
        run: npm run build # Ersätt detta med ditt faktiska byggkommando

      - name: Deploy to S3
        run: |
          aws s3 cp index.html s3://your-bucket-name/path-to-game/
          aws s3 cp styles.css s3://your-bucket-name/path-to-game/
          aws s3 cp -r your-assets-folder s3://your-bucket-name/path-to-game/ # Om du har andra resurser
